-- 众智释读公开意见与投票表。
-- 在 Supabase SQL Editor 中执行。当前网站提交仍走 Web3Forms；本表先用于公开展示与投票。

create extension if not exists pgcrypto;

create table if not exists public.suggestions (
  id uuid primary key default gen_random_uuid(),
  work_id text not null,
  type text not null check (type in ('transcription','punctuation','missingText')),
  page_no integer,
  line_no integer,
  column_no integer,
  glyph_id text,
  current_text text not null,
  suggested_text text not null,
  reason text not null,
  reference_text text,
  nickname text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.suggestion_votes (
  id bigint generated by default as identity primary key,
  suggestion_id uuid not null references public.suggestions(id) on delete cascade,
  voter_id text not null,
  vote_value smallint not null check (vote_value in (-1,1)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (suggestion_id,voter_id)
);

create or replace view public.suggestions_public as
select
  s.id,s.work_id,s.type,s.page_no,s.line_no,s.column_no,s.glyph_id,
  s.current_text,s.suggested_text,s.reason,s.reference_text,s.nickname,s.created_at,
  count(v.id) filter (where v.vote_value=1)::int as up_count,
  count(v.id) filter (where v.vote_value=-1)::int as down_count
from public.suggestions s
left join public.suggestion_votes v on v.suggestion_id=s.id
where s.status='approved'
group by s.id;

grant select on public.suggestions_public to anon, authenticated;

alter table public.suggestions enable row level security;
alter table public.suggestion_votes enable row level security;

-- 浏览者只能读取审核通过的原始意见；公开页面主要读取 suggestions_public 视图。
drop policy if exists "read approved suggestions" on public.suggestions;
create policy "read approved suggestions" on public.suggestions
for select to anon, authenticated
using (status='approved');

-- 不直接允许匿名访问投票表，统一通过两个安全函数投票。
revoke all on public.suggestion_votes from anon, authenticated;

create or replace function public.cast_community_vote(
  p_suggestion_id uuid,
  p_voter_id text,
  p_vote_value smallint
) returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if p_vote_value not in (-1,1) then
    raise exception 'invalid vote value';
  end if;
  if length(coalesce(p_voter_id,''))<8 or length(p_voter_id)>120 then
    raise exception 'invalid voter id';
  end if;
  if not exists(select 1 from public.suggestions where id=p_suggestion_id and status='approved') then
    raise exception 'suggestion is not public';
  end if;
  insert into public.suggestion_votes(suggestion_id,voter_id,vote_value)
  values(p_suggestion_id,p_voter_id,p_vote_value)
  on conflict(suggestion_id,voter_id)
  do update set vote_value=excluded.vote_value,updated_at=now();
end;
$$;

create or replace function public.remove_community_vote(
  p_suggestion_id uuid,
  p_voter_id text
) returns void
language sql
security definer
set search_path=public
as $$
  delete from public.suggestion_votes
  where suggestion_id=p_suggestion_id and voter_id=p_voter_id;
$$;

grant execute on function public.cast_community_vote(uuid,text,smallint) to anon, authenticated;
grant execute on function public.remove_community_vote(uuid,text) to anon, authenticated;

-- Realtime：在 Supabase Dashboard 的 Database > Replication 中，也可手动确认已启用这两张表。
alter publication supabase_realtime add table public.suggestions;
alter publication supabase_realtime add table public.suggestion_votes;

-- 三条可选测试数据。执行后请在 Table Editor 中确认 status=approved。
insert into public.suggestions(work_id,type,page_no,line_no,column_no,current_text,suggested_text,reason,reference_text,nickname,status)
values
('001','transcription',8,12,5,'德','首','根据字形上部结构及上下文判断，此处更接近“首”。','某拓本第8页','墨缘','approved'),
('001','transcription',9,3,7,'以','之','结合句意，前后语气衔接更通顺，应为“之”。','某拓本第9页','清风','approved'),
('001','punctuation',11,1,null,'大哉乾元，播物垂象。肇有书契，文籍生焉。','大哉乾元，播物垂象；肇有书契，文籍生焉。','前后两层语意相承，使用分号更能体现句间关系。','依据文意与骈文节奏','云中鹤','approved');
