
async function loadJSON(path){const r=await fetch(path);return await r.json();}
const params=new URLSearchParams(location.search);const id=params.get('id')||'001';let detail=null,pages=[],current=0;
function esc(s){return String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));}
function renderPlaceholder(){document.getElementById('detailHero').innerHTML=`<div><h1>碑帖 ${id}</h1><p class="meta">本条目前只保留跳转入口，具体图像、释文和背景资料后续整理。</p></div><a class="btn" href="gallery.html">返回总览</a>`;document.getElementById('reader').style.display='none';document.querySelector('.tabs').style.display='none';document.getElementById('tabContent').style.display='none';}
function renderHero(){let info=Object.entries(detail.basic_info||{}).map(([k,v])=>`<div class="info-item"><b>${k}</b><br>${esc(v)}</div>`).join('');document.getElementById('detailHero').innerHTML=`<div><p class="eyebrow">碑帖详情</p><h1>${detail.title}</h1><p>${detail.subtitle||''}</p><div class="info-grid">${info}</div></div><a class="btn" target="_blank" href="${detail.basic_info?.IIIF||'#'}">打开 IIIF 原站</a>`}
function fillPageSelect(){const sel=document.getElementById('pageSelect');sel.innerHTML=pages.map((p,i)=>`<option value="${i}">第${p.page}页｜${p.label}</option>`).join('');sel.onchange=()=>{current=Number(sel.value);renderPage();}}
function renderPage(){if(!pages.length)return;const p=pages[current];document.getElementById('pageSelect').value=current;document.getElementById('pageTitle').textContent=`第 ${p.page} 页｜${p.label}`;document.getElementById('pageText').textContent=p.text_clean||'本页暂无释文';const img=document.getElementById('pageImage');const pane=img.parentElement;pane.classList.remove('missing');img.style.display='block';img.src=p.image;img.onerror=()=>{img.style.display='none';pane.classList.add('missing')};history.replaceState(null,'',`detail.html?id=${id}&page=${p.page}#reader`)}
function renderTab(name){let html='';if(name==='guide'){html=`<h2>AI 分段导读</h2><p>${esc(detail.ai_summary)}</p>`+(detail.ai_sections||[]).map(x=>`<div class="ai-section"><h3>${esc(x.title)}</h3><p><b>原文片段：</b>${esc(x.original)}</p><p><b>导读：</b>${esc(x.guide)}</p><p><b>插画提示：</b>${esc(x.illustration_prompt)}</p></div>`).join('');}
if(name==='text'){html=`<h2 id="text">完整碑文</h2><div>${esc(detail.full_text)}</div>`}
if(name==='background'){html=`<h2 id="background">背景说明</h2><div>${esc(detail.background)}</div>`}
if(name==='version'){html=`<h2 id="version">版本题跋馆藏尺寸</h2><div>${esc(detail.version_note)}</div>`}
document.getElementById('tabContent').innerHTML=html;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));}
Promise.all([loadJSON('data/beitie_details.json'),loadJSON('data/beitie_pages.json')]).then(([d,p])=>{detail=(d.items||[]).find(x=>x.id===id);const pageObj=(p.items||[]).find(x=>x.id===id);if(!detail||!pageObj){renderPlaceholder();return;}pages=pageObj.pages||[];renderHero();fillPageSelect();const wanted=Number(params.get('page'));if(wanted){const idx=pages.findIndex(x=>x.page===wanted);if(idx>=0)current=idx;}renderPage();document.getElementById('prevPage').onclick=()=>{current=Math.max(0,current-1);renderPage()};document.getElementById('nextPage').onclick=()=>{current=Math.min(pages.length-1,current+1);renderPage()};document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>renderTab(b.dataset.tab));renderTab('guide');});
