
async function loadJSON(url){ const r = await fetch(url); return await r.json(); }
let graph, nodes, links, selected="道因法师碑", svg, W=980,H=620;
const typeColor={"碑帖":"#a6372a","人物":"#7d4b28","地点/机构":"#4f765d","收藏机构":"#596b92","收藏/地点":"#4f765d"};
function init(){svg=document.getElementById('relationGraph');loadJSON('data/beitie_people_graph.json').then(data=>{graph=data;nodes=data.nodes.map((d,i)=>({...d,x:W/2+Math.cos(i)*220,y:H/2+Math.sin(i)*150,vx:0,vy:0}));links=data.links;renderSamples(data.samples||[]);let q=new URLSearchParams(location.search).get('q');if(q){document.getElementById('personSearch').value=q;selectNode(q)}else updateInfo();tick();});searchPersonBtn.onclick=()=>searchPerson();personSearch.addEventListener('keydown',e=>{if(e.key==='Enter')searchPerson()})}
function renderSamples(arr){samplePeople.innerHTML=arr.map(n=>`<button onclick="selectNode('${n}')">${n}</button>`).join('')}
function searchPerson(){const q=personSearch.value.trim();if(q)selectNode(q)}
function selectNode(name){const found=nodes.find(n=>n.label.includes(name)||n.id.includes(name));if(found){selected=found.id;personSearch.value=found.label}else selected=name;updateInfo()}
function updateInfo(){const n=nodes.find(x=>x.id===selected)||nodes.find(x=>x.label.includes(selected));const info=graphInfo;if(!n){info.innerHTML=`<h2>未找到：${selected}</h2><p>当前样例网络没有该人物。后续接入45件碑帖人物名单后会扩展更多节点。</p>`;return}const related=links.filter(l=>l.source===n.id||l.target===n.id);info.innerHTML=`<h2>${n.label}</h2><p><span class="tag">${n.type}</span></p><p>${n.summary||''}</p><h3>相关关系</h3>`+(related.length?`<ul>${related.map(l=>`<li>${l.source} — <b>${l.relation}</b> — ${l.target}</li>`).join('')}</ul>`:'<p>暂无关系。</p>')}
function step(){if(!nodes)return;const center=nodes.find(n=>n.id===selected)||nodes[0];nodes.forEach((n,idx)=>{let tx=W/2,ty=H/2;if(n!==center){const rel=links.some(l=>(l.source===center.id&&l.target===n.id)||(l.target===center.id&&l.source===n.id));const angle=(idx/nodes.length)*Math.PI*2+Date.now()/9000;const radius=rel?220:310;tx=W/2+Math.cos(angle)*radius;ty=H/2+Math.sin(angle)*(rel?150:220)}n.vx+=(tx-n.x)*0.004+(Math.random()-.5)*0.08;n.vy+=(ty-n.y)*0.004+(Math.random()-.5)*0.08;n.vx*=0.88;n.vy*=0.88;n.x+=n.vx;n.y+=n.vy})}
function tick(){step();draw();requestAnimationFrame(tick)}
function draw(){if(!nodes)return;let html='';links.forEach(l=>{const s=nodes.find(n=>n.id===l.source),t=nodes.find(n=>n.id===l.target);if(!s||!t)return;const active=s.id===selected||t.id===selected;html+=`<line x1="${s.x}" y1="${s.y}" x2="${t.x}" y2="${t.y}" class="g-link ${active?'active':''}"/>`;if(active)html+=`<text x="${(s.x+t.x)/2}" y="${(s.y+t.y)/2}" class="g-rel">${l.relation}</text>`});nodes.forEach(n=>{const active=n.id===selected;const r=active?(n.size||28)*1.7:(n.size||24);html+=`<g class="g-node ${active?'active':''}" onclick="selectNode('${n.id}')"><circle cx="${n.x}" cy="${n.y}" r="${r}" fill="${typeColor[n.type]||'#87623e'}"/><text x="${n.x}" y="${n.y+5}" text-anchor="middle">${n.label}</text></g>`});svg.innerHTML=html}
window.selectNode=selectNode;init();
