from pathlib import Path

path = Path('detail.html')
text = path.read_text(encoding='utf-8')

if 'function refinedModelRect(box)' in text and 'modelPageBoxPaths(id,pageNo)' in text:
    raise SystemExit(0)

old_decl_start = 'const RAW_WORK_ID=String(new URLSearchParams(location.search).get("id")||"001");'
decl_start = text.index(old_decl_start)
decl_end = text.index('let currentPageIndex=', decl_start)
new_decl = '''const RAW_WORK_ID=String(new URLSearchParams(location.search).get("id")||"001");const WORK_ID=RAW_WORK_ID.includes("-")?RAW_WORK_ID:RAW_WORK_ID.padStart(3,"0");const PARENT_WORK_ID=WORK_ID.includes("-")?WORK_ID.split("-")[0]:WORK_ID;let EFFECTIVE_WORK_ID=WORK_ID;const IIIF_COORDINATE_PARENTS=new Set(["014","031"]);function usesIIIFCoordinatePolicy(){return IIIF_COORDINATE_PARENTS.has(PARENT_WORK_ID)}function modelShardPath(){const n=Number(PARENT_WORK_ID);if(!Number.isInteger(n)||n<1||n>45)return"";const start=Math.floor((n-1)/5)*5+1,end=Math.min(start+4,45);return`data/model_boxes/glyph_model_border_${String(start).padStart(3,"0")}_${String(end).padStart(3,"0")}.json`}function coordinateDataCandidates(){if(usesIIIFCoordinatePolicy())return[];const shard=modelShardPath();return shard?[shard]:[]}window.__COLUMN1_COORDINATE_POLICY__={workId:WORK_ID,parentId:PARENT_WORK_ID,mode:usesIIIFCoordinatePolicy()?"iiif":"model",modelPageRoot:"data/glyph_boxes/model_aligned_border_refined",modelShard:modelShardPath()};'''
text = text[:decl_start] + new_decl + text[decl_end:]

box_start = text.index('function pageBoxPath(')
box_end = text.index('function fallbackWorkForId', box_start)
new_boxes = '''function iiifPageBoxPath(id,pageNo){return`data/glyph_boxes/iiif/${id}/page_${String(pageNo).padStart(4,"0")}.json`}function modelPageBoxPaths(id,pageNo){const name=`page_${String(pageNo).padStart(4,"0")}.json`,ids=[id];if(PARENT_WORK_ID&&!ids.includes(PARENT_WORK_ID))ids.push(PARENT_WORK_ID);return ids.map(workId=>`data/glyph_boxes/model_aligned_border_refined/${workId}/${name}`)}function estimateRows(n){if(n<=0)return 1;if(n<=10)return Math.ceil(n/2);if(n<=32)return Math.ceil(n/3);if(n<=70)return Math.ceil(n/5);return Math.ceil(Math.sqrt(n*1.8))}function refinedModelRect(box){if(box.border_x!==undefined&&box.border_y!==undefined&&box.border_w!==undefined&&box.border_h!==undefined)return{x:+box.border_x,y:+box.border_y,w:+box.border_w,h:+box.border_h};return null}function normalizeGlyphBoxRecord(box,pageObj,i,total,mode){const r=mode==="model"?refinedModelRect(box):getRect(box);if(!r||!isFinite(r.x)||!isFinite(r.y)||!isFinite(r.w)||!isFinite(r.h)||r.w<=0||r.h<=0)return null;const ch=String(box.char||box.text||box.value||"");const rows=estimateRows(total);return{glyph_id:box.glyph_id||`${EFFECTIVE_WORK_ID}_p${pageObj.canvas_index}_b${i+1}`,char:ch?ch[0]:"",text:ch?ch[0]:"",order_in_page:box.order_in_page||box.annotation_index||i+1,canvas_index:pageObj.canvas_index,canvas_label:pageObj.canvas_label||pageObj.label||pageObj.canvas_index,local_image:pageObj.image,canvas_width:box.canvas_width||pageObj.canvas_width,canvas_height:box.canvas_height||pageObj.canvas_height,bbox_x:r.x,bbox_y:r.y,bbox_w:r.w,bbox_h:r.h,bbox:[r.x,r.y,r.w,r.h],auto_col:box.auto_col!==undefined?+box.auto_col:Math.floor(i/rows),auto_row:box.auto_row!==undefined?+box.auto_row:i%rows,source:mode==="model"?"model_aligned_border_refined":String(box.source||"iiif")}}async function loadPageGlyphBoxes(id,pageObj,mode){const paths=mode==="iiif"?[iiifPageBoxPath(id,pageObj.canvas_index)]:modelPageBoxPaths(id,pageObj.canvas_index);for(const path of paths){const data=await safeFetchJSON(path);if(!Array.isArray(data)||!data.length)continue;const normalized=data.map((box,i)=>normalizeGlyphBoxRecord(box,pageObj,i,data.length,mode)).filter(Boolean);if(normalized.length)return normalized}return[]}'''
text = text[:box_start] + new_boxes + text[box_end:]

old_page = 'const p=pages[currentPageIndex],fallbackItems=p.items||[];currentGlyphs=fallbackItems;const useIIIF=usesIIIFCoordinatePolicy();const perPageBoxes=useIIIF?await loadPageGlyphBoxes(EFFECTIVE_WORK_ID,p):[];if(token!==loadPageToken)return;currentGlyphs=useIIIF?(perPageBoxes.length?perPageBoxes:fallbackItems):fallbackItems;window.__COLUMN1_ACTIVE_COORDINATE_SOURCE__={workId:EFFECTIVE_WORK_ID,parentId:PARENT_WORK_ID,page:p.canvas_index,mode:useIIIF?"iiif":"model",recordCount:currentGlyphs.length,sources:[...new Set(currentGlyphs.map(g=>String(g.source||"")))]};'
new_page = 'const p=pages[currentPageIndex],fallbackItems=p.items||[];currentGlyphs=fallbackItems;const useIIIF=usesIIIFCoordinatePolicy(),coordinateMode=useIIIF?"iiif":"model";const perPageBoxes=await loadPageGlyphBoxes(EFFECTIVE_WORK_ID,p,coordinateMode);if(token!==loadPageToken)return;currentGlyphs=perPageBoxes.length?perPageBoxes:fallbackItems;const sources=[...new Set(currentGlyphs.map(g=>String(g.source||"")))],activeMode=useIIIF?"iiif":perPageBoxes.length?"model_aligned_border_refined":sources.includes("model_border_refined")?"model_border_refined":"model_unavailable",firstRect=currentGlyphs.length?getRect(currentGlyphs[0]):null;window.__COLUMN1_ACTIVE_COORDINATE_SOURCE__={workId:EFFECTIVE_WORK_ID,parentId:PARENT_WORK_ID,page:p.canvas_index,mode:activeMode,recordCount:currentGlyphs.length,sources,firstRect:firstRect?{x:firstRect.x,y:firstRect.y,w:firstRect.w,h:firstRect.h}:null};'
if old_page not in text:
    raise SystemExit('loadPage anchor missing')
text = text.replace(old_page, new_page, 1)

path.write_text(text, encoding='utf-8')
